name = "IdentifiabilityODE"
uuid = "cf7bdac0-b945-4905-b5ad-bc3f1a757483"
authors = ["Alexey Ovchinnikov <Alexey.Ovchinnikov@qc.cuny.edu>","Gleb Pogudin <gleb.pogudin@polytechnique.edu>","Ilia Ilmer <i.ilmer@icloud.com>"]
version = "0.1.0"

[deps]
GroebnerBasis = "e39c9192-ea4d-5e15-9584-a488c6d614bd"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Oscar = "f1435218-dba5-11e9-1e4d-f1a5fab5fc13"
Singular = "bcd08a7b-43d2-5ff7-b6d4-c458787f915c"