name: "SIAN Tests for Julia"
on: [push]
jobs:
  run-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: ["^1.5.1", "nightly"]
        julia-arch: [x64, x86]
        os: [macOS-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
      - uses: julia-actions/julia-buildpkg@latest
      - uses: julia-actions/julia-runtest@latest
      - run: ls
      - run: julia tests/runtests.jl
