name: "SIAN Tests for Julia"
on:
  push:
    branches:
      - main
      - develop
    paths-ignore:
    - 'README.md'
    - 'Dockerfile'
    - '.gitignore'
jobs:
  run-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: ['1.5.3'] 
        os: [macos-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }} 
      - uses: julia-actions/julia-buildpkg@latest
        with:
          version: ${{ matrix.julia-version }} 
      - uses: julia-actions/julia-runtest@latest
        with:
          version: ${{ matrix.julia-version }}
